### ISSUE TITLE
Errore traduzione

### ISSUE THREAD

**Issue by dariopnc** [MicrosoftDocs/windowsserverdocs.it-it#3]
Gli Id sono errati, perché probabilmente "tradotti" dalla versione inglese. In quella sono contenuti gli ID corretti

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e6a56536-cc84-ce8a-c18c-d141e5641bfe
* Version Independent ID: bb28b451-4056-74d9-d388-3d17eabaa0ff
* Content: [ID del set](https://docs.microsoft.com/it-it/windows-server/administration/windows-commands/set-id#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/set-id.md](https://github.com/MicrosoftDocs/windowsserverdocs.it-it/blob/live/WindowsServerDocs/administration/windows-commands/set-id.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @dariopnc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dariopnc
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/it-it/windows-server/administration/windows-commands/set-id#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
