### ISSUE TITLE
Get-WindowsFeature FS-SMB1 not recognized

### ISSUE THREAD

**Issue by Enozagar** [MicrosoftDocs/windowsserverdocs.it-it#5]
Hi all, 
as reported, I'd have liked to check SMB v1 on my PC. As reported below, the log shows that this command isn't recognized.

PS C:\WINDOWS\system32&gt; Get-WindowsFeature FS-SMB1
Get-WindowsFeature : Termine 'Get-WindowsFeature' non riconosciuto come nome di cmdlet, funzione, programma eseguibile
o file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
+ Get-WindowsFeature FS-SMB1
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [Come rilevare, abilitare e disabilitare SMBv1, SMBv2 e SMBv3 in Windows](https://docs.microsoft.com/it-it/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#feedback)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs.it-it/blob/live/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by srvbpigh** [comment]
Hello, @Enozagar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Enozagar, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/4142. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by QuiGonJames** [comment]
Are you running this on Windows Server 2012 R2 or 2016? If not, it is not the correct command.
The section in MS Docs with that command specifies these OSes.

But you mentioned you were running it on your PC. Assuming Windows 10 or 8(.1), you need to run: **Get-WindowsOptionalFeature –Online –FeatureName SMB1Protocol**
This is specified in the section for these OSes:
[MS Docs Link](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#windows-81-and-windows-10-powershell-method)

**Comment by illfated** [comment]
Same link as above, just made openly visible as plain text:
- https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#windows-81-and-windows-10-powershell-method
