### ISSUE TITLE
D Parameter incorrect switch for Italian

### ISSUE THREAD

**Issue by zepteraln** [MicrosoftDocs/windowsserverdocs.it-it#6]
Hey,
For your attention, the listed switch for Italian is incorrect in this documentation for the D Parameter, a Yes switch is rejected for Italian local and S should be used instead.

It should be a S (Si) or N (No) switch for Italian, not Yes or No.

e.g.:

 /d {S | N}

Shlomi

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: dc00bc99-0b73-9ffd-f3bb-64569079dbcb
* Version Independent ID: a8aadbc5-1ea3-71e6-7989-25daf422636d
* Content: [takeown](https://docs.microsoft.com/it-it/windows-server/administration/windows-commands/takeown#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/takeown.md](https://github.com/MicrosoftDocs/windowsserverdocs.it-it/blob/live/WindowsServerDocs/administration/windows-commands/takeown.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by srvbpigh** [comment]
Hello, @zepteraln
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @zepteraln 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
